// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- getter-schema ---
import { TreeNodeSchema as GetterSchemaTreeNodeSchema, NestedRecordSchema as GetterSchemaNestedRecordSchema, CallbackSchema as GetterSchemaCallbackSchema } from "../fixtures/getter-schema";
import type {
  TreeNodeInput as GetterSchemaTreeNodeInput,
  TreeNodeOutput as GetterSchemaTreeNodeOutput,
  NestedRecordInput as GetterSchemaNestedRecordInput,
  NestedRecordOutput as GetterSchemaNestedRecordOutput,
  CallbackInput as GetterSchemaCallbackInput,
  CallbackOutput as GetterSchemaCallbackOutput,
} from "./getter-schema";

describe("Type equality tests", () => {
  describe("getter-schema", () => {
    it("TreeNodeSchema input matches v.InferInput", () => {
      expectTypeOf<GetterSchemaTreeNodeInput>().toEqualTypeOf<v.InferInput<typeof GetterSchemaTreeNodeSchema>>();
    });

    it("TreeNodeSchema output matches v.InferOutput", () => {
      expectTypeOf<GetterSchemaTreeNodeOutput>().toEqualTypeOf<v.InferOutput<typeof GetterSchemaTreeNodeSchema>>();
    });

    it("NestedRecordSchema input matches v.InferInput", () => {
      expectTypeOf<GetterSchemaNestedRecordInput>().toEqualTypeOf<v.InferInput<typeof GetterSchemaNestedRecordSchema>>();
    });

    it("NestedRecordSchema output matches v.InferOutput", () => {
      expectTypeOf<GetterSchemaNestedRecordOutput>().toEqualTypeOf<v.InferOutput<typeof GetterSchemaNestedRecordSchema>>();
    });

    it("CallbackSchema input matches v.InferInput", () => {
      expectTypeOf<GetterSchemaCallbackInput>().toEqualTypeOf<v.InferInput<typeof GetterSchemaCallbackSchema>>();
    });

    it("CallbackSchema output matches v.InferOutput", () => {
      expectTypeOf<GetterSchemaCallbackOutput>().toEqualTypeOf<v.InferOutput<typeof GetterSchemaCallbackSchema>>();
    });
  });
});
