// Generated by vinfer - Do not edit manually

export type TreeNodeInput = {
  value: string;
  children?: TreeNodeInput[];
};

export type TreeNodeOutput = {
  value: string;
  children?: TreeNodeOutput[];
};

export type NestedRecordInput = {
  name: string;
  items: {
    [x: string]: NestedRecordInput;
  };
};

export type NestedRecordOutput = {
  name: string;
  items: {
    [x: string]: NestedRecordOutput;
  };
};

export type CallbackInput = {
  name: string;
  callback: Function;
  optionalCallback?: Function | undefined;
};

export type CallbackOutput = {
  name: string;
  callback: Function;
  optionalCallback?: Function | undefined;
};
